# handlers/main.yml
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start nas_mount service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: started

- name: Reload NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
